# Client-C

# debRed
- targets:
  labels:
    tenant: client-c
    cluster: client-c-vm-prod
    instance: debRed
    environment: production
    platform: vm
    role: alloy-test-client
    host: debRed
    exporter: alloy
    collection_method: push

# ubRed
- targets:
  labels:
    tenant: client-c
    cluster: client-c-vm-prod
    instance: ubRed
    environment: production
    platform: vm
    role: alloy-test-client
    host: ubRed
    exporter: alloy
    collection_method: push


# ubRed2
- targets:
  labels:
    tenant: client-c
    cluster: client-c-vm-prod
    instance: ubRed2
    environment: production
    platform: vm
    role: alloy-test-client
    host: ubRed2
    exporter: alloy
    collection_method: push


# Cross-Over Server from Client-A: db-svr02
#- targets:
#  labels:
#    tenant: Client-B
#    instance: db-svr01
#    environment: production
#    role: alloy-client
#    host: db-svr01
#    exporter: alloy
#    collection_method: push
