# Monitor the Stack itself
- targets:
    - localhost:9090
  # Prometheus
  labels:
    tenant: internal
    environment: production
    role: control-plane
    service: prometheus

# Loki
- targets:
    - loki:3100
  labels:
    tenant: internal
    environment: production
    role: control-plane
    service: loki

# Grafana
- targets:
    - grafana:3000
  labels:
    tenant: internal
    environment: production
    role: control-plane
    service: grafana

# Promtail
- targets:
    - promtail:9080
  labels:
    tenant: internal
    environment: production
    role: control-plane
    service: promtail

# Blackbox
- targets:
    - blackbox:9115
  labels:
    tenant: internal
    environment: production
    role: control-plane
    service: blackbox

# MinIO
- targets:
    - minio:9000
  labels:
    tenant: internal
    environment: production
    role: control-plane
    service: minio
