# Internal Monitoring - Monitoring the HOST VM
- targets:
    - node-exporter:9100
  labels:
    tenant: internal
    instance: monitoring-vm
    environment: production
    role: control-plane
    host: monitoring-vm
    exporter: node

# Client Servers

# Client-A
- targets:
    - 192.168.0.12:9100
  labels:
    tenant: Client-A
    instance: db-svr02
    environment: production
    role: client
    host: db-svr02
    exporter: node


#- targets:
#    - <ip_address>:9100
#  labels:
#    tenant: <client_name>
    # Used to distinguish between types of servers (production, staging, dev)
#    environment:
    # Identifies what the Server Does
#    role: <server_job>
    # Name for the server (display)
#    host:
    # Label to tell what type of metrics are being sent
#    exporter: node
