# Internal Monitoring - Monitoring the HOST VM
- targets:
    - node-exporter:9100
  labels:
    tenant: internal
    cluster: internal-monitoring-prod
    instance: monitoring-vm
    environment: production
    platform: docker
    role: control-plane
    host: monitoring-vm
    exporter: node

# Internal Server Monitoring - Cluster
# Prometheus Node Exporter for Bare Metal Servers

- targets:
    - 100.121.87.54:9100
  labels:
    tenant: internal
    cluster: homelab-physical
    instance: Blue
    environment: production
    platform: metal
    role: ansible
    host: debBlue
    exporter: node

- targets:
    - 192.168.0.216:9100
  labels:
    tenant: internal
    cluster: homelab-physical
    instance: Gray
    environment: production
    platform: metal
    host: fedGray
    role: k3s-server
    exporter: node

- targets:
    - 100.126.196.70:9100
  labels:
    tenant: internal
    cluster: homelab-physical
    instance: Shadow
    platform: metal
    environment: production
    host: shadow
    role: visual-monitor
    exporter: node


# Client Servers

# Client-A
- targets:
    - 192.168.0.12:9100
  labels:
    tenant: client-a
    cluster: client-a-vm-prod
    instance: db-svr02
    environment: production
    platform: vm
    role: database
    host: db-svr02
    exporter: node

- targets:
    - 192.168.0.172:9100
  labels:
    tenant: client-a
    cluster: client-a-vm-prod
    instance: db-svr01
    environment: production
    platform: vm
    role: database
    host: db-svr01
    exporter: node

- targets:
    - 192.168.0.11:9100
  labels:
    tenant: client-a
    cluster: client-a-vm-prod
    instance: sys-monitor
    environment: production
    platform: vm
    role: monitor
    host: sys-monitor
    exporter: node

- targets:
    - 192.168.0.139:9100
  labels:
    tenant: client-a
    cluster: client-a-vm-prod
    instance: irin-webserver
    environment: production
    platform: vm
    role: webserver
    host: irin-webserver
    exporter: node

# Client-B

- targets:
    - 192.168.0.121:9100
  labels:
    tenant: client-b
    cluster: client-b-vm-prod
    instance: file-server
    environment: production
    platform: vm
    role: file-server
    host: file-server
    exporter: node

- targets:
    - 192.168.0.120:9100
  labels:
    tenant: client-b
    cluster: client-b-vm-prod
    instance: mtg-webserver
    environment: production
    platform: vm
    role: webserver
    host: mtg-webserver
    exporter: node



#- targets:
#    - <ip_address>:9100
#  labels:
#    tenant: <client_name>
    # Used to distinguish between types of servers (production, staging, dev)
#    environment:
    # Identifies what the Server Does
#    role: <server_job>
    # Name for the server (display)
#    host:
    # Label to tell what type of metrics are being sent
#    exporter: node
