# Global Settings that apply to all scrape jobs
global:
  # How often to scrape targets
  scrape_interval: 15s
  # How often to evaluate alerting rules
  evaluation_interval: 15s

# Load alerting and recording rules
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
      - targets:
          - alertmanager:9093


# List all targets/services that Prometheus will monitor

# Internal Monitor - Monitors the entire stack (loki, grafana, promtail, blackbox, minio)
scrape_configs:
  - job_name: 'internal'
    file_sd_configs:
      - files:
        - /etc/prometheus/file_sd/internal_monitoring.yml
        refresh_interval: 30s

  # File-Based Service discovery for node_exporter
  # Add new nodes to /etc/prometheus/file_sd/prom_nodes.yml
  - job_name: 'nodes'
    file_sd_configs:
      - files:
        - /etc/prometheus/file_sd/prom_nodes.yml
        # How often to re-read the file for changes
        refresh_interval: 30s

  # Blackbox - Monitor external websites
  # Add new domains to /etc/prometheus/file_sd/blackbox_addr.yml
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
        - /etc/prometheus/file_sd/blackbox_addr.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  # Cadvisor - Internal Docker Metrics
  - job_name: 'internal-docker'
    file_sd_configs:
      - files:
        - /etc/prometheus/file_sd/docker-monitor.yml
        refresh_interval: 30s
